sudo: required
services: 
  - docker

before_install:
  - docker build -t thetalorian/docker-react -f Dockerfile.dev .

script:
  - docker run thetalorian/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-west-1-315066089897
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
